[[development_tests]]
= Development Testing
:_basedir: ../
:_imagesdir: images/

== Component Tests

DataNucleus uses JUnit for unit testing. The traditional style of "unit" test are included with the project that 
they are testing. For example "core" has some "unit" tests, and these are run when you build the project. In general
DataNucleus doesn't have many of this style of tests (you're welcome to write some) because the more important aspect
of testing is the actual reading/writing involving the datastore (see below).

== End-to-End Tests

__End-to-End tests__ also use JUnit, and are available in the GitHub DataNucleus repository https://github.com/datanucleus/tests[tests].
In these tests we persist objects in a datastore, and test the result. There are several scenarios for this type of test, because JDO/JPA 
have many aspects. By this we mean that we separate our tests into what they test. When developing anything, the tests should be the guiding 
light as to whether you should be checking anything in to GitHub. __If your change breaks things, you shouldn't check things in.__
We have tests divided by the persistence API that they are testing; look under the directories
https://github.com/datanucleus/tests/tree/master/jdo[jdo], https://github.com/datanucleus/tests/tree/master/jpa[jpa] and 
https://github.com/datanucleus/tests/tree/master/rest[rest].

=== framework

All DataNucleus end-to-end tests are based around a framework and this requires building first before running any tests. 
Navigate into the https://github.com/datanucleus/tests/tree/master/framework[framework] directory, and build and install it by typing

-----
mvn clean install
-----

This builds the jar under "target" and installs it into your Maven repository.


=== framework.maven

This is a Maven plugin that allows some of the tests to be run with different configurations. You should build and install it by typing

-----
mvn clean install
-----

This builds the jar under "target" and installs it into your Maven repository.


=== samples

The https://github.com/datanucleus/tests/tree/master/samples[samples] project provides typical model classes 
to be persisted, with all different types of relations. This project doesn't define _how_ the classes are persisted, 
just what the classes are. They are then usable by all persistence APIs. You should build and install it by typing

-----
mvn clean install
-----

This builds the jar under "target" and installs it into your Maven repository.


=== End-to-End Test Scenarios

So we have now built the _framework_, _framework.maven_ and _samples_ projects and are ready to run any of the "scenarios". 
There are many scenarios including

* Tests for JDO API
** __jdo/general__ - General tests for JDO
** __jdo/identity__ - Tests for JDO that run with both application and datastore identity types
** __jdo/jta__ - Tests for using JTA transactions with JDO
** __jdo/geospatial__ - Tests for use spatial types with JDO
** __jdo/rdbms__ - Tests specific to RDBMS, using JDO
** __jdo/ldap__ - Tests specific to LDAP, using JDO
** __jdo/spreadsheet__ - Tests specific to Excel and ODF, using JDO
** __jdo/hbase__ - Tests for basic handling with HBase, using JDO
** __jdo/mongodb__ - Tests for basic handling with MongoDB, using JDO
* Tests for JPA API
** __jpa/general__ - General tests for JPA
** __jpa/jta__ - Tests for using JTA transaction with JPA
** __jpa/geospatial__ - Tests for using spatial types with JPA
** __jpa/rdbms__ - Tests specific to RDBMS, using JPA
* Tests for REST API
** __rest/general__ - Tests using the REST API

To run a test scenario, go into the scenario project and type

-----
mvn clean test
-----

This then runs the tests for that scenario. There are also occasionally additional tests under _org.datanucleus.tests.knownbugs_ and 
_org.datanucleus.tests.newfeatures_ intended for incorporation into the test scenario at some later point; these are not run by default.

__To run the tests on a different datastore (default=H2)__ type

-----
mvn clean test -Pmysql
-----

or replace "mysql" with "postgresql", "oracle", "mongodb", "hbase" etc

Long term strategy is to just have the overall test scenarios that apply just to JDO or JPA and drop the datastore-specific scenarios 
except where providing some feature specific to that datastore. Reality is that we don't have resource to do this yet, so typically 
run such as _test.jdo.mongodb_ for testing MongoDB, which obviously only tests a small subset of what ought to be tested. 
__Offering your time to make all store plugins more feature complete is the only way this task will be performed.__


[[add_unit_test]]
=== Adding Unit Tests

Where you feel that our unit tests do not adequately cover functionality, you should add a test. Please follow the following process

. Decide which scenario your test fits into (e.g jdo/general, jpa/general)
. Look at the available model samples and choose one.
. Write your unit test, extending one of the common base classes, for example __JDOPersistenceTestCase__, or __JPAPersistenceTestCase__
. Run your test.
. Raise an issue and attach your testcase to the issue


=== Alternate Test Configurations

All tests run with a default test configuration (see the files in _framework_ under 
https://github.com/datanucleus/tests/tree/master/framework/src/conf[src/conf]).
You can, with some test suites, run alternate test configurations. This is achieved using the _framework.maven_ Maven plugin.

. Look for a configuration file under _src/conf_ of _framework_ such as _optimistic-conf.properties_. These properties are used to override the default properties
. Run the tests with _-Dtest.configs=optimistic_ or _-Dtest.configs=optimistic,pessimistic_ for example


== JDO TCK

DataNucleus GitHub "master" passes the JDO TCK, and hence is a fully-compliant implementation of JDO. All developers should run this TCK from time to time to validate any changes.
The following shows the results of the TCK as proof of compatibility. You can, of course, simply run DataNucleus yourself with the JDO TCK 
(downloadable from the http://db.apache.org/jdo[Apache JDO Project]). JDO is an open standard, being developed by the Apache JDO project. 
As yet there are no other fully compliant implementations of JDO, publishing their results on a publically visible website; don't believe their 
claims of compliance unless they post this output below. The tests below were run with DataNucleus GitHub "master" (v5.0) on 25/Mar/2016.

-----
	dsid-runonce-junit.txt:
	    OK Tests run: 002, Time: 002 seconds.
	dsid-instancecallbacks-junit.txt:
	    OK Tests run: 016, Time: 003 seconds.
	dsid-jdohelper-junit.txt:
	    OK Tests run: 045, Time: 002 seconds.
	dsid-pm-junit.txt:
	    OK Tests run: 168, Time: 027 seconds.
	dsid-pmf-junit.txt:
	    OK Tests run: 068, Time: 017 seconds.
	dsid-detach-junit.txt:
	    OK Tests run: 018, Time: 003 seconds.
	dsid-embeddedInheritance-junit.txt:
	    OK Tests run: 004, Time: 002 seconds.
	dsid-enhancement-junit.txt:
	    OK Tests run: 031, Time: 001 seconds.
	dsid-extents-junit.txt:
	    OK Tests run: 013, Time: 004 seconds.
	dsid-fetchplan-junit.txt:
	    OK Tests run: 021, Time: 002 seconds.
	dsid-fetchgroup-junit.txt:
	    OK Tests run: 035, Time: 002 seconds.
	dsid-lifecycle-junit.txt:
	    OK Tests run: 017, Time: 005 seconds.
	dsid-models-junit.txt:
	    OK Tests run: 050, Time: 075 seconds.
	dsid-models1-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-query-junit.txt:
	    OK Tests run: 162, Time: 019 seconds.
	dsid-jdoql-junit.txt:
	    OK Tests run: 153, Time: 029 seconds.
	dsid-jdoql1-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-transactions-junit.txt:
	    OK Tests run: 030, Time: 003 seconds.
	dsid-companyNoRelationships-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyEmbedded-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-company1-1Relationships-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-company1-MRelationships-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyM-MRelationships-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	dsid-companyAllRelationships-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyMapWithoutJoin-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	dsid-companyListWithoutJoin-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	dsid-companyPMClass-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	dsid-companyPMInterface-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotated1-1RelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotated1-MRelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	dsid-companyAnnotatedAllRelationshipsFCConcrete-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotatedAllRelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotatedAllRelationshipsPCConcrete-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotatedAllRelationshipsJPAConcrete-junit.txt:
	    OK Tests run: 001, Time: 001 seconds.
	dsid-companyAnnotatedAllRelationshipsJPAPM-junit.txt:
	    OK Tests run: 001, Time: 001 seconds.
	dsid-companyAnnotatedAllRelationshipsPCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotatedAllRelationshipsPIPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotatedEmbeddedFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotatedM-MRelationshipsFCConcrete-junit.txt:
	    OK Tests run: 001, Time: 006 seconds.
	dsid-companyAnnotatedM-MRelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotatedNoRelationshipsFCConcrete-junit.txt:
	    OK Tests run: 001, Time: 004 seconds.
	dsid-companyAnnotatedNoRelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotatedNoRelationshipsPCConcrete-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotatedEmbeddedJPAConcrete-junit.txt:
	    OK Tests run: 001, Time: 001 seconds.
	dsid-companyAnnotatedEmbeddedJPAPM-junit.txt:
	    OK Tests run: 001, Time: 001 seconds.
	dsid-companyAnnotatedNoRelationshipsPCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyAnnotatedNoRelationshipsPIPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-companyOverrideAnnotatedAllRelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-inheritance1-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-inheritance2-junit.txt:
	    OK Tests run: 001, Time: 001 seconds.
	dsid-inheritance3-junit.txt:
	    OK Tests run: 001, Time: 001 seconds.
	dsid-inheritance4-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	dsid-relationshipAllRelationships-junit.txt:
	    OK Tests run: 034, Time: 007 seconds.
	dsid-relationshipNoRelationships-junit.txt:
	    OK Tests run: 015, Time: 005 seconds.
	dsid-schemaAttributeClass-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	dsid-schemaAttributeOrm-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	dsid-schemaAttributePackage-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	dsid-compoundIdentity-junit.txt:
	    OK Tests run: 001, Time: 001 seconds.
	dsid-throwOnUnknownStandardProperties-junit.txt:
	    OK Tests run: 002, Time: 000 seconds.
	app-instancecallbacks-junit.txt:
	    OK Tests run: 016, Time: 002 seconds.
	app-jdohelper-junit.txt:
	    OK Tests run: 045, Time: 002 seconds.
	app-pm-junit.txt:
	    OK Tests run: 168, Time: 026 seconds.
	app-pmf-junit.txt:
	    OK Tests run: 068, Time: 017 seconds.
	app-detach-junit.txt:
	    OK Tests run: 018, Time: 002 seconds.
	app-embeddedInheritance-junit.txt:
	    OK Tests run: 004, Time: 002 seconds.
	app-enhancement-junit.txt:
	    OK Tests run: 031, Time: 001 seconds.
	app-extents-junit.txt:
	    OK Tests run: 013, Time: 003 seconds.
	app-fetchplan-junit.txt:
	    OK Tests run: 021, Time: 002 seconds.
	app-fetchgroup-junit.txt:
	    OK Tests run: 035, Time: 001 seconds.
	app-lifecycle-junit.txt:
	    OK Tests run: 017, Time: 004 seconds.
	app-models-junit.txt:
	    OK Tests run: 050, Time: 068 seconds.
	app-models1-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-query-junit.txt:
	    OK Tests run: 162, Time: 016 seconds.
	app-jdoql-junit.txt:
	    OK Tests run: 153, Time: 022 seconds.
	app-jdoql1-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-transactions-junit.txt:
	    OK Tests run: 030, Time: 003 seconds.
	app-companyNoRelationships-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	app-companyEmbedded-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-company1-1Relationships-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	app-company1-MRelationships-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	app-companyM-MRelationships-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	app-companyAllRelationships-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyMapWithoutJoin-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	app-companyListWithoutJoin-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyPMClass-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyPMInterface-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotated1-1RelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotated1-MRelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedAllRelationshipsFCConcrete-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedAllRelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedAllRelationshipsPCConcrete-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedAllRelationshipsJPAConcrete-junit.txt:
	    OK Tests run: 001, Time: 004 seconds.
	app-companyAnnotatedAllRelationshipsJPAPM-junit.txt:
	    OK Tests run: 001, Time: 004 seconds.
	app-companyAnnotatedAllRelationshipsPCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedAllRelationshipsPIPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedEmbeddedFCPM-junit.txt:
	    OK Tests run: 001, Time: 004 seconds.
	app-companyAnnotatedM-MRelationshipsFCConcrete-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedM-MRelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedNoRelationshipsFCConcrete-junit.txt:
	    OK Tests run: 001, Time: 004 seconds.
	app-companyAnnotatedNoRelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedNoRelationshipsPCConcrete-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedEmbeddedJPAConcrete-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedEmbeddedJPAPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedNoRelationshipsPCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyAnnotatedNoRelationshipsPIPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-companyOverrideAnnotatedAllRelationshipsFCPM-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-inheritance1-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-inheritance2-junit.txt:
	    OK Tests run: 001, Time: 001 seconds.
	app-inheritance3-junit.txt:
	    OK Tests run: 001, Time: 001 seconds.
	app-inheritance4-junit.txt:
	    OK Tests run: 001, Time: 003 seconds.
	app-relationshipAllRelationships-junit.txt:
	    OK Tests run: 034, Time: 008 seconds.
	app-relationshipNoRelationships-junit.txt:
	    OK Tests run: 015, Time: 005 seconds.
	app-schemaAttributeClass-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	app-schemaAttributeOrm-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	app-schemaAttributePackage-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	app-compoundIdentity-junit.txt:
	    OK Tests run: 001, Time: 002 seconds.
	app-throwOnUnknownStandardProperties-junit.txt:
	    OK Tests run: 002, Time: 000 seconds.

	Total tests run: 1846.
	All (117) configurations passed.
-----

== JPA 1 TCK

All releases of DataNucleus since v1 pass the JPA1 (JSR 220) TCK. JPA1 is a standard developed in private by the JCP. 
Its discussions were not open and the TCK is not freely downloadable and so users cannot check any such claims for compliance. 
This is in direct contrast to the JDO standard. We leave it to users to decide how they feel about that. The tests below were run 
with JPA TCK 1.0b and DataNucleus GitHub master (v5.0) on 25/Mar/2016 against PostgreSQL 9.4.

-----
	Completed running 435 tests.
	Number of Tests Passed      = 435
	Number of Tests Failed      = 0
	Number of Tests with Errors = 0
-----

Sadly I'm not legally allowed to disclose any further details about these tests due to having to sign an NDA just to get hold of the TCK.

== JPA 2+ TCK

As mentioned in https://datanucleus.wordpress.com/2010/04/16/jpa-and-the-role-of-compliance/[this blog post] we applied for the JPA 2.0 TCK 
on 8th February 2010. This request was handled by Jonathan Nimer and Patrick Curran at SUN/Oracle. They (eventually) provided us with a form 
to sign and return to gain access to the JPA2 TCK. This was returned to them at the end of April 2010 to their address of _4150 Network Circle, Santa Clara, CA 95054, USA_. 
We have since prompted them on more than 3 occasions when we will be getting access to this secret TCK. They have still not provided it
and as a result __we are forced to claim full compliance with the JPA2 spec__ since testing is being hidden from us. 
The only possible conclusions for this unwillingness to provide the TCK as per their terms and conditions are either incompetence, 
or deliberate prevention of access. How do you, the user, feel about an organisation like Oracle preventing a level playing field for such technologies?

Since the JPA "group" have still not published an official JPA 2.0 / 2.1 API jar into Maven Central we really feel that their priorities are not 
in the best interests of you the user. The basic minimum should be publish the official JPA API jars, and get a public open source TCK. 
Once those are in place then we can talk.

As a measure of how well DataNucleus is compliant with the JPA TCK, in addition to our own tests, it is also tested as part of the tests written for
the https://travis-ci.org/Blazebit/blaze-persistence[Blaze Persistence Framework] and passes their tests as well as the likes of Hibernate, and better
than EclipseLink, and bear in mind that their tests are centred around Hibernate features not DataNucleus features, and incorporate not just standard JPA behaviour 
but also items that have been requested for inclusion in later releases of JPA.

== Jakarta Persistence TCK

There does not seem to be a separate TCK for Jakarta Persistence; it seems to be part of some huge Jakarta EE TCK. 
Since DataNucleus implements just one part of that we have no time for working out what that means for a Jakarta Persistence implementation.
The JPA1 TCK had no placeholder for bytecode enhancement and we had to hack in a way of incorporating enhancement, but all files are seemingly different
here anyway, so unclear how to proceed on that either. If it is important to you, then go and work it out and report back.


== Databases Notes

=== Database setup for running tests

Each test project is run against a datastore (as defined above). The configuration of the datastores is stored under framework 
https://github.com/datanucleus/tests/tree/master/framework/src/conf[src/conf]. Some tests require two database instances, 
which is why for every database there exist two files, e.g. `maven.datanucleus.datastore=hsql` refers to both

* framework/src/conf/datanucleus-hsql.__1__.properties, and
* framework/src/conf/datanucleus-hsql.__2__.properties

The default database configured in the test projects is H2.

Following are notes about running the DataNucleus unit tests with particular databases.

=== Oracle 10.2

If you face the issue _ORA-12519, TNS:no appropriate service handler_, try increasing the parameters _sessions_ and _processes_ to 300 and 
_open\_cursors_ to 1000. To change these values in Oracle, issue the following statements.

-----
	alter system set open_cursors = 1000 scope=spfile
	alter system set sessions = 300 scope=spfile
	alter system set processes = 300 scope=spfile
-----

Refer also to the Oracle spfile (see also _initXE.ora_ or _init.ora_)
-----
	*.processes=300
	*.sessions=300
	*.open_cursors=1000
-----

If you face the issue _ORA-01000: maximum open cursors exceeded_, try increasing the parameter _open\_cursors_ to 1000 in the file _initXE.ora_ or _init.ora_.
-----
	*.open_cursors=1000
-----

If you face OutOfMemory errors, increase the _Xms_ and _Xmx_ JVM args for running the junit tests.
